### ISSUE TITLE
Can I run it in UnityEditor?

### ISSUE THREAD

**Issue by pacifinapacific** [cookieofcode/hololens2-unity-uwp-starter#1]
Thanks for the great project.
I want to use this project to study mediacapture in hololens2. How can I run this project, is it possible to run it on unity editor?

**Comment by cookieofcode** [comment]
Hi @pacifinapacific 

The idea is that you can use shared resources between a UWP project and a Unity project. This way, you can develop UWP features faster using the UWP project. Please note, that you can not use UWP in the Unity Editor, meaning you have to build the project and test it on the HoloLens directly. You can find the Unity project in https://github.com/cookieofcode/hololens2-unity-uwp-starter/tree/main/Unity. 

If you need to have a camera in the Unity Editor, take a look at https://github.com/cookieofcode/LabAssistVision. It allows to use the webcam in the Unity Editor and the MediaCapture on the HoloLens. Please note that using the webcam in the Unity Editor without Holographic Remoting, you'll receive hard-coded spatial coordinates and not the ones from the HoloLens.

**Comment by pacifinapacific** [comment]
Thank you very much. I have deployed it to hololesn2. But it only shows the pink object in the front.
Is there anything I need to do between opening the Unity project and Build?
